//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvaApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class deduction
    {
        public int IdDeduction { get; set; }
        public Nullable<int> num { get; set; }
        public string designation { get; set; }
        public Nullable<System.DateTime> DateFact { get; set; }
        public Nullable<double> TauxTva { get; set; }
        public Nullable<decimal> MontHT { get; set; }
        public Nullable<decimal> MontTva { get; set; }
        public Nullable<decimal> MontTTC { get; set; }
        public Nullable<double> Prorata { get; set; }
        public string ModePaiment { get; set; }
        public Nullable<System.DateTime> DatePaiment { get; set; }
        public string observation { get; set; }
        public Nullable<int> C_IdFournisseur { get; set; }
        public Nullable<int> C_IdPeriode { get; set; }
    
        public virtual fournisseur fournisseur { get; set; }
        public virtual periode periode { get; set; }
    }
}
