//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvaApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class exercice
    {
        public exercice()
        {
            this.periodes = new HashSet<periode>();
        }
    
        public int IdExercice { get; set; }
        public Nullable<int> Annee { get; set; }
        public Nullable<System.DateTime> Date_debut { get; set; }
        public Nullable<System.DateTime> Date_fin { get; set; }
        public string TypeEx { get; set; }
        public Nullable<decimal> ChiffreAffaire { get; set; }
        public Nullable<bool> Cloture { get; set; }
        public Nullable<System.DateTime> DateClosure { get; set; }
        public Nullable<int> C_IdSociete { get; set; }
    
        public virtual societe societe { get; set; }
        public virtual ICollection<periode> periodes { get; set; }
    }
}
