//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvaApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class fournisseur
    {
        public fournisseur()
        {
            this.deductions = new HashSet<deduction>();
        }
    
        public int IdFournisseur { get; set; }
        public string RaisonFiscale { get; set; }
        public Nullable<int> IdFiscale { get; set; }
        public Nullable<int> Ice { get; set; }
        public string Adresse { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<deduction> deductions { get; set; }
    }
}
