//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvaApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TvaAppBDEntities1 : DbContext
    {
        public TvaAppBDEntities1()
            : base("name=TvaAppBDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<associe> associes { get; set; }
        public DbSet<deduction> deductions { get; set; }
        public DbSet<exercice> exercices { get; set; }
        public DbSet<fournisseur> fournisseurs { get; set; }
        public DbSet<periode> periodes { get; set; }
        public DbSet<societe> societes { get; set; }
        public DbSet<utilisateur> utilisateurs { get; set; }
    }
}
