//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvaApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class periode
    {
        public periode()
        {
            this.deductions = new HashSet<deduction>();
        }
    
        public int IdPeriode { get; set; }
        public string NomPeriode { get; set; }
        public Nullable<decimal> MonDeclaTVA { get; set; }
        public Nullable<System.DateTime> DateDeclaration { get; set; }
        public Nullable<int> C_IdExercice { get; set; }
    
        public virtual ICollection<deduction> deductions { get; set; }
        public virtual exercice exercice { get; set; }
    }
}
