//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvaApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class societe
    {
        public societe()
        {
            this.associes = new HashSet<associe>();
            this.exercices = new HashSet<exercice>();
        }
   
        public int IdSociete { get; set; }
        [Required]
        public string SiegeSoc { get; set; }
        [Required]
        public string Tel { get; set; }
        [Required]
        public string Fax { get; set; }
        [Required]
        public string FormeJuridique { get; set; }
        [Required][RangeAttribute(1,1000)]
        public Nullable<int> IdFiscal { get; set; }
        [Required]
        public Nullable<int> NumTaxPro { get; set; }
        [Required]
        public string Regime { get; set; }
        [Required]
        public Nullable<int> Ice { get; set; }
        [Required]
        public Nullable<int> RegistreCommerce { get; set; }
        [Required]
        public Nullable<int> NumCnss { get; set; }
        [Required]
        public string ModComptable { get; set; }
        [Required]
        public string LoginDGI { get; set; }
        [Required]
        public string MdpDgi { get; set; }
        [Required]
        public Nullable<decimal> Capital { get; set; }
        [Required]
        public string Activite { get; set; }
        [Required]
        public string TypeRegime { get; set; }
        [Required]
        public string commune { get; set; }
        [Required]
        public virtual ICollection<associe> associes { get; set; }
        [Required]
        public virtual ICollection<exercice> exercices { get; set; }
    }
}
