//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("TvaAppBDModel", "FK__associe___IdSoci__3B75D760", "societe", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TvaDeclarationApp.societe), "associe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TvaDeclarationApp.associe), true)]
[assembly: EdmRelationshipAttribute("TvaAppBDModel", "FK__deduction___IdFo__45F365D3", "fournisseur", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TvaDeclarationApp.fournisseur), "deduction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TvaDeclarationApp.deduction), true)]
[assembly: EdmRelationshipAttribute("TvaAppBDModel", "FK__deduction___IdPe__46E78A0C", "periode", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TvaDeclarationApp.periode), "deduction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TvaDeclarationApp.deduction), true)]
[assembly: EdmRelationshipAttribute("TvaAppBDModel", "FK__exercice___IdSoc__3E52440B", "societe", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TvaDeclarationApp.societe), "exercice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TvaDeclarationApp.exercice), true)]
[assembly: EdmRelationshipAttribute("TvaAppBDModel", "FK__periode___IdExer__412EB0B6", "exercice", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TvaDeclarationApp.exercice), "periode", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TvaDeclarationApp.periode), true)]

#endregion

namespace TvaDeclarationApp
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class TvaAppBDEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet TvaAppBDEntities à l'aide de la chaîne de connexion trouvée dans la section 'TvaAppBDEntities' du fichier de configuration d'application.
        /// </summary>
        public TvaAppBDEntities() : base("name=TvaAppBDEntities", "TvaAppBDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet TvaAppBDEntities.
        /// </summary>
        public TvaAppBDEntities(string connectionString) : base(connectionString, "TvaAppBDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet TvaAppBDEntities.
        /// </summary>
        public TvaAppBDEntities(EntityConnection connection) : base(connection, "TvaAppBDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<associe> associes
        {
            get
            {
                if ((_associes == null))
                {
                    _associes = base.CreateObjectSet<associe>("associes");
                }
                return _associes;
            }
        }
        private ObjectSet<associe> _associes;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<deduction> deductions
        {
            get
            {
                if ((_deductions == null))
                {
                    _deductions = base.CreateObjectSet<deduction>("deductions");
                }
                return _deductions;
            }
        }
        private ObjectSet<deduction> _deductions;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<exercice> exercices
        {
            get
            {
                if ((_exercices == null))
                {
                    _exercices = base.CreateObjectSet<exercice>("exercices");
                }
                return _exercices;
            }
        }
        private ObjectSet<exercice> _exercices;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<fournisseur> fournisseurs
        {
            get
            {
                if ((_fournisseurs == null))
                {
                    _fournisseurs = base.CreateObjectSet<fournisseur>("fournisseurs");
                }
                return _fournisseurs;
            }
        }
        private ObjectSet<fournisseur> _fournisseurs;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<periode> periodes
        {
            get
            {
                if ((_periodes == null))
                {
                    _periodes = base.CreateObjectSet<periode>("periodes");
                }
                return _periodes;
            }
        }
        private ObjectSet<periode> _periodes;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<societe> societes
        {
            get
            {
                if ((_societes == null))
                {
                    _societes = base.CreateObjectSet<societe>("societes");
                }
                return _societes;
            }
        }
        private ObjectSet<societe> _societes;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<utilisateur> utilisateurs
        {
            get
            {
                if ((_utilisateurs == null))
                {
                    _utilisateurs = base.CreateObjectSet<utilisateur>("utilisateurs");
                }
                return _utilisateurs;
            }
        }
        private ObjectSet<utilisateur> _utilisateurs;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet associes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToassocies(associe associe)
        {
            base.AddObject("associes", associe);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet deductions. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTodeductions(deduction deduction)
        {
            base.AddObject("deductions", deduction);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet exercices. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToexercices(exercice exercice)
        {
            base.AddObject("exercices", exercice);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet fournisseurs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTofournisseurs(fournisseur fournisseur)
        {
            base.AddObject("fournisseurs", fournisseur);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet periodes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToperiodes(periode periode)
        {
            base.AddObject("periodes", periode);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet societes. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddTosocietes(societe societe)
        {
            base.AddObject("societes", societe);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet utilisateurs. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToutilisateurs(utilisateur utilisateur)
        {
            base.AddObject("utilisateurs", utilisateur);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TvaAppBDModel", Name="associe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class associe : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet associe.
        /// </summary>
        /// <param name="idAssocie">Valeur initiale de la propriété IdAssocie.</param>
        public static associe Createassocie(global::System.Int32 idAssocie)
        {
            associe associe = new associe();
            associe.IdAssocie = idAssocie;
            return associe;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdAssocie
        {
            get
            {
                return _IdAssocie;
            }
            set
            {
                if (_IdAssocie != value)
                {
                    OnIdAssocieChanging(value);
                    ReportPropertyChanging("IdAssocie");
                    _IdAssocie = StructuralObject.SetValidValue(value, "IdAssocie");
                    ReportPropertyChanged("IdAssocie");
                    OnIdAssocieChanged();
                }
            }
        }
        private global::System.Int32 _IdAssocie;
        partial void OnIdAssocieChanging(global::System.Int32 value);
        partial void OnIdAssocieChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomAssocie
        {
            get
            {
                return _NomAssocie;
            }
            set
            {
                OnNomAssocieChanging(value);
                ReportPropertyChanging("NomAssocie");
                _NomAssocie = StructuralObject.SetValidValue(value, true, "NomAssocie");
                ReportPropertyChanged("NomAssocie");
                OnNomAssocieChanged();
            }
        }
        private global::System.String _NomAssocie;
        partial void OnNomAssocieChanging(global::System.String value);
        partial void OnNomAssocieChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrenomAssocie
        {
            get
            {
                return _PrenomAssocie;
            }
            set
            {
                OnPrenomAssocieChanging(value);
                ReportPropertyChanging("PrenomAssocie");
                _PrenomAssocie = StructuralObject.SetValidValue(value, true, "PrenomAssocie");
                ReportPropertyChanged("PrenomAssocie");
                OnPrenomAssocieChanged();
            }
        }
        private global::System.String _PrenomAssocie;
        partial void OnPrenomAssocieChanging(global::System.String value);
        partial void OnPrenomAssocieChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumCin
        {
            get
            {
                return _NumCin;
            }
            set
            {
                OnNumCinChanging(value);
                ReportPropertyChanging("NumCin");
                _NumCin = StructuralObject.SetValidValue(value, true, "NumCin");
                ReportPropertyChanged("NumCin");
                OnNumCinChanged();
            }
        }
        private global::System.String _NumCin;
        partial void OnNumCinChanging(global::System.String value);
        partial void OnNumCinChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumCarSejour
        {
            get
            {
                return _NumCarSejour;
            }
            set
            {
                OnNumCarSejourChanging(value);
                ReportPropertyChanging("NumCarSejour");
                _NumCarSejour = StructuralObject.SetValidValue(value, true, "NumCarSejour");
                ReportPropertyChanged("NumCarSejour");
                OnNumCarSejourChanged();
            }
        }
        private global::System.String _NumCarSejour;
        partial void OnNumCarSejourChanging(global::System.String value);
        partial void OnNumCarSejourChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_nai
        {
            get
            {
                return _Date_nai;
            }
            set
            {
                OnDate_naiChanging(value);
                ReportPropertyChanging("Date_nai");
                _Date_nai = StructuralObject.SetValidValue(value, "Date_nai");
                ReportPropertyChanged("Date_nai");
                OnDate_naiChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_nai;
        partial void OnDate_naiChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_naiChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adresse
        {
            get
            {
                return _Adresse;
            }
            set
            {
                OnAdresseChanging(value);
                ReportPropertyChanging("Adresse");
                _Adresse = StructuralObject.SetValidValue(value, true, "Adresse");
                ReportPropertyChanged("Adresse");
                OnAdresseChanged();
            }
        }
        private global::System.String _Adresse;
        partial void OnAdresseChanging(global::System.String value);
        partial void OnAdresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fonction
        {
            get
            {
                return _Fonction;
            }
            set
            {
                OnFonctionChanging(value);
                ReportPropertyChanging("Fonction");
                _Fonction = StructuralObject.SetValidValue(value, true, "Fonction");
                ReportPropertyChanged("Fonction");
                OnFonctionChanged();
            }
        }
        private global::System.String _Fonction;
        partial void OnFonctionChanging(global::System.String value);
        partial void OnFonctionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Part
        {
            get
            {
                return _Part;
            }
            set
            {
                OnPartChanging(value);
                ReportPropertyChanging("Part");
                _Part = StructuralObject.SetValidValue(value, "Part");
                ReportPropertyChanged("Part");
                OnPartChanged();
            }
        }
        private Nullable<global::System.Double> _Part;
        partial void OnPartChanging(Nullable<global::System.Double> value);
        partial void OnPartChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C_IdSociete
        {
            get
            {
                return _C_IdSociete;
            }
            set
            {
                OnC_IdSocieteChanging(value);
                ReportPropertyChanging("C_IdSociete");
                _C_IdSociete = StructuralObject.SetValidValue(value, "C_IdSociete");
                ReportPropertyChanged("C_IdSociete");
                OnC_IdSocieteChanged();
            }
        }
        private Nullable<global::System.Int32> _C_IdSociete;
        partial void OnC_IdSocieteChanging(Nullable<global::System.Int32> value);
        partial void OnC_IdSocieteChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TvaAppBDModel", "FK__associe___IdSoci__3B75D760", "societe")]
        public societe societe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<societe>("TvaAppBDModel.FK__associe___IdSoci__3B75D760", "societe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<societe>("TvaAppBDModel.FK__associe___IdSoci__3B75D760", "societe").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<societe> societeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<societe>("TvaAppBDModel.FK__associe___IdSoci__3B75D760", "societe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<societe>("TvaAppBDModel.FK__associe___IdSoci__3B75D760", "societe", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TvaAppBDModel", Name="deduction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class deduction : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet deduction.
        /// </summary>
        /// <param name="idDeduction">Valeur initiale de la propriété IdDeduction.</param>
        public static deduction Creatededuction(global::System.Int32 idDeduction)
        {
            deduction deduction = new deduction();
            deduction.IdDeduction = idDeduction;
            return deduction;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDeduction
        {
            get
            {
                return _IdDeduction;
            }
            set
            {
                if (_IdDeduction != value)
                {
                    OnIdDeductionChanging(value);
                    ReportPropertyChanging("IdDeduction");
                    _IdDeduction = StructuralObject.SetValidValue(value, "IdDeduction");
                    ReportPropertyChanged("IdDeduction");
                    OnIdDeductionChanged();
                }
            }
        }
        private global::System.Int32 _IdDeduction;
        partial void OnIdDeductionChanging(global::System.Int32 value);
        partial void OnIdDeductionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> num
        {
            get
            {
                return _num;
            }
            set
            {
                OnnumChanging(value);
                ReportPropertyChanging("num");
                _num = StructuralObject.SetValidValue(value, "num");
                ReportPropertyChanged("num");
                OnnumChanged();
            }
        }
        private Nullable<global::System.Int32> _num;
        partial void OnnumChanging(Nullable<global::System.Int32> value);
        partial void OnnumChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String designation
        {
            get
            {
                return _designation;
            }
            set
            {
                OndesignationChanging(value);
                ReportPropertyChanging("designation");
                _designation = StructuralObject.SetValidValue(value, true, "designation");
                ReportPropertyChanged("designation");
                OndesignationChanged();
            }
        }
        private global::System.String _designation;
        partial void OndesignationChanging(global::System.String value);
        partial void OndesignationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateFact
        {
            get
            {
                return _DateFact;
            }
            set
            {
                OnDateFactChanging(value);
                ReportPropertyChanging("DateFact");
                _DateFact = StructuralObject.SetValidValue(value, "DateFact");
                ReportPropertyChanged("DateFact");
                OnDateFactChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateFact;
        partial void OnDateFactChanging(Nullable<global::System.DateTime> value);
        partial void OnDateFactChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> TauxTva
        {
            get
            {
                return _TauxTva;
            }
            set
            {
                OnTauxTvaChanging(value);
                ReportPropertyChanging("TauxTva");
                _TauxTva = StructuralObject.SetValidValue(value, "TauxTva");
                ReportPropertyChanged("TauxTva");
                OnTauxTvaChanged();
            }
        }
        private Nullable<global::System.Double> _TauxTva;
        partial void OnTauxTvaChanging(Nullable<global::System.Double> value);
        partial void OnTauxTvaChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MontHT
        {
            get
            {
                return _MontHT;
            }
            set
            {
                OnMontHTChanging(value);
                ReportPropertyChanging("MontHT");
                _MontHT = StructuralObject.SetValidValue(value, "MontHT");
                ReportPropertyChanged("MontHT");
                OnMontHTChanged();
            }
        }
        private Nullable<global::System.Decimal> _MontHT;
        partial void OnMontHTChanging(Nullable<global::System.Decimal> value);
        partial void OnMontHTChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MontTva
        {
            get
            {
                return _MontTva;
            }
            set
            {
                OnMontTvaChanging(value);
                ReportPropertyChanging("MontTva");
                _MontTva = StructuralObject.SetValidValue(value, "MontTva");
                ReportPropertyChanged("MontTva");
                OnMontTvaChanged();
            }
        }
        private Nullable<global::System.Decimal> _MontTva;
        partial void OnMontTvaChanging(Nullable<global::System.Decimal> value);
        partial void OnMontTvaChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MontTTC
        {
            get
            {
                return _MontTTC;
            }
            set
            {
                OnMontTTCChanging(value);
                ReportPropertyChanging("MontTTC");
                _MontTTC = StructuralObject.SetValidValue(value, "MontTTC");
                ReportPropertyChanged("MontTTC");
                OnMontTTCChanged();
            }
        }
        private Nullable<global::System.Decimal> _MontTTC;
        partial void OnMontTTCChanging(Nullable<global::System.Decimal> value);
        partial void OnMontTTCChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Prorata
        {
            get
            {
                return _Prorata;
            }
            set
            {
                OnProrataChanging(value);
                ReportPropertyChanging("Prorata");
                _Prorata = StructuralObject.SetValidValue(value, "Prorata");
                ReportPropertyChanged("Prorata");
                OnProrataChanged();
            }
        }
        private Nullable<global::System.Double> _Prorata;
        partial void OnProrataChanging(Nullable<global::System.Double> value);
        partial void OnProrataChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModePaiment
        {
            get
            {
                return _ModePaiment;
            }
            set
            {
                OnModePaimentChanging(value);
                ReportPropertyChanging("ModePaiment");
                _ModePaiment = StructuralObject.SetValidValue(value, true, "ModePaiment");
                ReportPropertyChanged("ModePaiment");
                OnModePaimentChanged();
            }
        }
        private global::System.String _ModePaiment;
        partial void OnModePaimentChanging(global::System.String value);
        partial void OnModePaimentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DatePaiment
        {
            get
            {
                return _DatePaiment;
            }
            set
            {
                OnDatePaimentChanging(value);
                ReportPropertyChanging("DatePaiment");
                _DatePaiment = StructuralObject.SetValidValue(value, "DatePaiment");
                ReportPropertyChanged("DatePaiment");
                OnDatePaimentChanged();
            }
        }
        private Nullable<global::System.DateTime> _DatePaiment;
        partial void OnDatePaimentChanging(Nullable<global::System.DateTime> value);
        partial void OnDatePaimentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String observation
        {
            get
            {
                return _observation;
            }
            set
            {
                OnobservationChanging(value);
                ReportPropertyChanging("observation");
                _observation = StructuralObject.SetValidValue(value, true, "observation");
                ReportPropertyChanged("observation");
                OnobservationChanged();
            }
        }
        private global::System.String _observation;
        partial void OnobservationChanging(global::System.String value);
        partial void OnobservationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C_IdFournisseur
        {
            get
            {
                return _C_IdFournisseur;
            }
            set
            {
                OnC_IdFournisseurChanging(value);
                ReportPropertyChanging("C_IdFournisseur");
                _C_IdFournisseur = StructuralObject.SetValidValue(value, "C_IdFournisseur");
                ReportPropertyChanged("C_IdFournisseur");
                OnC_IdFournisseurChanged();
            }
        }
        private Nullable<global::System.Int32> _C_IdFournisseur;
        partial void OnC_IdFournisseurChanging(Nullable<global::System.Int32> value);
        partial void OnC_IdFournisseurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C_IdPeriode
        {
            get
            {
                return _C_IdPeriode;
            }
            set
            {
                OnC_IdPeriodeChanging(value);
                ReportPropertyChanging("C_IdPeriode");
                _C_IdPeriode = StructuralObject.SetValidValue(value, "C_IdPeriode");
                ReportPropertyChanged("C_IdPeriode");
                OnC_IdPeriodeChanged();
            }
        }
        private Nullable<global::System.Int32> _C_IdPeriode;
        partial void OnC_IdPeriodeChanging(Nullable<global::System.Int32> value);
        partial void OnC_IdPeriodeChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TvaAppBDModel", "FK__deduction___IdFo__45F365D3", "fournisseur")]
        public fournisseur fournisseur
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fournisseur>("TvaAppBDModel.FK__deduction___IdFo__45F365D3", "fournisseur").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fournisseur>("TvaAppBDModel.FK__deduction___IdFo__45F365D3", "fournisseur").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<fournisseur> fournisseurReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<fournisseur>("TvaAppBDModel.FK__deduction___IdFo__45F365D3", "fournisseur");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<fournisseur>("TvaAppBDModel.FK__deduction___IdFo__45F365D3", "fournisseur", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TvaAppBDModel", "FK__deduction___IdPe__46E78A0C", "periode")]
        public periode periode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<periode>("TvaAppBDModel.FK__deduction___IdPe__46E78A0C", "periode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<periode>("TvaAppBDModel.FK__deduction___IdPe__46E78A0C", "periode").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<periode> periodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<periode>("TvaAppBDModel.FK__deduction___IdPe__46E78A0C", "periode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<periode>("TvaAppBDModel.FK__deduction___IdPe__46E78A0C", "periode", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TvaAppBDModel", Name="exercice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class exercice : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet exercice.
        /// </summary>
        /// <param name="idExercice">Valeur initiale de la propriété IdExercice.</param>
        public static exercice Createexercice(global::System.Int32 idExercice)
        {
            exercice exercice = new exercice();
            exercice.IdExercice = idExercice;
            return exercice;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdExercice
        {
            get
            {
                return _IdExercice;
            }
            set
            {
                if (_IdExercice != value)
                {
                    OnIdExerciceChanging(value);
                    ReportPropertyChanging("IdExercice");
                    _IdExercice = StructuralObject.SetValidValue(value, "IdExercice");
                    ReportPropertyChanged("IdExercice");
                    OnIdExerciceChanged();
                }
            }
        }
        private global::System.Int32 _IdExercice;
        partial void OnIdExerciceChanging(global::System.Int32 value);
        partial void OnIdExerciceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Annee
        {
            get
            {
                return _Annee;
            }
            set
            {
                OnAnneeChanging(value);
                ReportPropertyChanging("Annee");
                _Annee = StructuralObject.SetValidValue(value, "Annee");
                ReportPropertyChanged("Annee");
                OnAnneeChanged();
            }
        }
        private Nullable<global::System.Int32> _Annee;
        partial void OnAnneeChanging(Nullable<global::System.Int32> value);
        partial void OnAnneeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_debut
        {
            get
            {
                return _Date_debut;
            }
            set
            {
                OnDate_debutChanging(value);
                ReportPropertyChanging("Date_debut");
                _Date_debut = StructuralObject.SetValidValue(value, "Date_debut");
                ReportPropertyChanged("Date_debut");
                OnDate_debutChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_debut;
        partial void OnDate_debutChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_debutChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_fin
        {
            get
            {
                return _Date_fin;
            }
            set
            {
                OnDate_finChanging(value);
                ReportPropertyChanging("Date_fin");
                _Date_fin = StructuralObject.SetValidValue(value, "Date_fin");
                ReportPropertyChanged("Date_fin");
                OnDate_finChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_fin;
        partial void OnDate_finChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_finChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TypeEx
        {
            get
            {
                return _TypeEx;
            }
            set
            {
                OnTypeExChanging(value);
                ReportPropertyChanging("TypeEx");
                _TypeEx = StructuralObject.SetValidValue(value, true, "TypeEx");
                ReportPropertyChanged("TypeEx");
                OnTypeExChanged();
            }
        }
        private global::System.String _TypeEx;
        partial void OnTypeExChanging(global::System.String value);
        partial void OnTypeExChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ChiffreAffaire
        {
            get
            {
                return _ChiffreAffaire;
            }
            set
            {
                OnChiffreAffaireChanging(value);
                ReportPropertyChanging("ChiffreAffaire");
                _ChiffreAffaire = StructuralObject.SetValidValue(value, "ChiffreAffaire");
                ReportPropertyChanged("ChiffreAffaire");
                OnChiffreAffaireChanged();
            }
        }
        private Nullable<global::System.Decimal> _ChiffreAffaire;
        partial void OnChiffreAffaireChanging(Nullable<global::System.Decimal> value);
        partial void OnChiffreAffaireChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Cloture
        {
            get
            {
                return _Cloture;
            }
            set
            {
                OnClotureChanging(value);
                ReportPropertyChanging("Cloture");
                _Cloture = StructuralObject.SetValidValue(value, "Cloture");
                ReportPropertyChanged("Cloture");
                OnClotureChanged();
            }
        }
        private Nullable<global::System.Boolean> _Cloture;
        partial void OnClotureChanging(Nullable<global::System.Boolean> value);
        partial void OnClotureChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateClosure
        {
            get
            {
                return _DateClosure;
            }
            set
            {
                OnDateClosureChanging(value);
                ReportPropertyChanging("DateClosure");
                _DateClosure = StructuralObject.SetValidValue(value, "DateClosure");
                ReportPropertyChanged("DateClosure");
                OnDateClosureChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateClosure;
        partial void OnDateClosureChanging(Nullable<global::System.DateTime> value);
        partial void OnDateClosureChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C_IdSociete
        {
            get
            {
                return _C_IdSociete;
            }
            set
            {
                OnC_IdSocieteChanging(value);
                ReportPropertyChanging("C_IdSociete");
                _C_IdSociete = StructuralObject.SetValidValue(value, "C_IdSociete");
                ReportPropertyChanged("C_IdSociete");
                OnC_IdSocieteChanged();
            }
        }
        private Nullable<global::System.Int32> _C_IdSociete;
        partial void OnC_IdSocieteChanging(Nullable<global::System.Int32> value);
        partial void OnC_IdSocieteChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TvaAppBDModel", "FK__exercice___IdSoc__3E52440B", "societe")]
        public societe societe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<societe>("TvaAppBDModel.FK__exercice___IdSoc__3E52440B", "societe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<societe>("TvaAppBDModel.FK__exercice___IdSoc__3E52440B", "societe").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<societe> societeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<societe>("TvaAppBDModel.FK__exercice___IdSoc__3E52440B", "societe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<societe>("TvaAppBDModel.FK__exercice___IdSoc__3E52440B", "societe", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TvaAppBDModel", "FK__periode___IdExer__412EB0B6", "periode")]
        public EntityCollection<periode> periodes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<periode>("TvaAppBDModel.FK__periode___IdExer__412EB0B6", "periode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<periode>("TvaAppBDModel.FK__periode___IdExer__412EB0B6", "periode", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TvaAppBDModel", Name="fournisseur")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class fournisseur : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet fournisseur.
        /// </summary>
        /// <param name="idFournisseur">Valeur initiale de la propriété IdFournisseur.</param>
        public static fournisseur Createfournisseur(global::System.Int32 idFournisseur)
        {
            fournisseur fournisseur = new fournisseur();
            fournisseur.IdFournisseur = idFournisseur;
            return fournisseur;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFournisseur
        {
            get
            {
                return _IdFournisseur;
            }
            set
            {
                if (_IdFournisseur != value)
                {
                    OnIdFournisseurChanging(value);
                    ReportPropertyChanging("IdFournisseur");
                    _IdFournisseur = StructuralObject.SetValidValue(value, "IdFournisseur");
                    ReportPropertyChanged("IdFournisseur");
                    OnIdFournisseurChanged();
                }
            }
        }
        private global::System.Int32 _IdFournisseur;
        partial void OnIdFournisseurChanging(global::System.Int32 value);
        partial void OnIdFournisseurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RaisonFiscale
        {
            get
            {
                return _RaisonFiscale;
            }
            set
            {
                OnRaisonFiscaleChanging(value);
                ReportPropertyChanging("RaisonFiscale");
                _RaisonFiscale = StructuralObject.SetValidValue(value, true, "RaisonFiscale");
                ReportPropertyChanged("RaisonFiscale");
                OnRaisonFiscaleChanged();
            }
        }
        private global::System.String _RaisonFiscale;
        partial void OnRaisonFiscaleChanging(global::System.String value);
        partial void OnRaisonFiscaleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdFiscale
        {
            get
            {
                return _IdFiscale;
            }
            set
            {
                OnIdFiscaleChanging(value);
                ReportPropertyChanging("IdFiscale");
                _IdFiscale = StructuralObject.SetValidValue(value, "IdFiscale");
                ReportPropertyChanged("IdFiscale");
                OnIdFiscaleChanged();
            }
        }
        private Nullable<global::System.Int32> _IdFiscale;
        partial void OnIdFiscaleChanging(Nullable<global::System.Int32> value);
        partial void OnIdFiscaleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ice
        {
            get
            {
                return _Ice;
            }
            set
            {
                OnIceChanging(value);
                ReportPropertyChanging("Ice");
                _Ice = StructuralObject.SetValidValue(value, "Ice");
                ReportPropertyChanged("Ice");
                OnIceChanged();
            }
        }
        private Nullable<global::System.Int32> _Ice;
        partial void OnIceChanging(Nullable<global::System.Int32> value);
        partial void OnIceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adresse
        {
            get
            {
                return _Adresse;
            }
            set
            {
                OnAdresseChanging(value);
                ReportPropertyChanging("Adresse");
                _Adresse = StructuralObject.SetValidValue(value, true, "Adresse");
                ReportPropertyChanged("Adresse");
                OnAdresseChanged();
            }
        }
        private global::System.String _Adresse;
        partial void OnAdresseChanging(global::System.String value);
        partial void OnAdresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                OnTelChanging(value);
                ReportPropertyChanging("Tel");
                _Tel = StructuralObject.SetValidValue(value, true, "Tel");
                ReportPropertyChanged("Tel");
                OnTelChanged();
            }
        }
        private global::System.String _Tel;
        partial void OnTelChanging(global::System.String value);
        partial void OnTelChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TvaAppBDModel", "FK__deduction___IdFo__45F365D3", "deduction")]
        public EntityCollection<deduction> deductions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<deduction>("TvaAppBDModel.FK__deduction___IdFo__45F365D3", "deduction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<deduction>("TvaAppBDModel.FK__deduction___IdFo__45F365D3", "deduction", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TvaAppBDModel", Name="periode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class periode : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet periode.
        /// </summary>
        /// <param name="idPeriode">Valeur initiale de la propriété IdPeriode.</param>
        public static periode Createperiode(global::System.Int32 idPeriode)
        {
            periode periode = new periode();
            periode.IdPeriode = idPeriode;
            return periode;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPeriode
        {
            get
            {
                return _IdPeriode;
            }
            set
            {
                if (_IdPeriode != value)
                {
                    OnIdPeriodeChanging(value);
                    ReportPropertyChanging("IdPeriode");
                    _IdPeriode = StructuralObject.SetValidValue(value, "IdPeriode");
                    ReportPropertyChanged("IdPeriode");
                    OnIdPeriodeChanged();
                }
            }
        }
        private global::System.Int32 _IdPeriode;
        partial void OnIdPeriodeChanging(global::System.Int32 value);
        partial void OnIdPeriodeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomPeriode
        {
            get
            {
                return _NomPeriode;
            }
            set
            {
                OnNomPeriodeChanging(value);
                ReportPropertyChanging("NomPeriode");
                _NomPeriode = StructuralObject.SetValidValue(value, true, "NomPeriode");
                ReportPropertyChanged("NomPeriode");
                OnNomPeriodeChanged();
            }
        }
        private global::System.String _NomPeriode;
        partial void OnNomPeriodeChanging(global::System.String value);
        partial void OnNomPeriodeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MonDeclaTVA
        {
            get
            {
                return _MonDeclaTVA;
            }
            set
            {
                OnMonDeclaTVAChanging(value);
                ReportPropertyChanging("MonDeclaTVA");
                _MonDeclaTVA = StructuralObject.SetValidValue(value, "MonDeclaTVA");
                ReportPropertyChanged("MonDeclaTVA");
                OnMonDeclaTVAChanged();
            }
        }
        private Nullable<global::System.Decimal> _MonDeclaTVA;
        partial void OnMonDeclaTVAChanging(Nullable<global::System.Decimal> value);
        partial void OnMonDeclaTVAChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateDeclaration
        {
            get
            {
                return _DateDeclaration;
            }
            set
            {
                OnDateDeclarationChanging(value);
                ReportPropertyChanging("DateDeclaration");
                _DateDeclaration = StructuralObject.SetValidValue(value, "DateDeclaration");
                ReportPropertyChanged("DateDeclaration");
                OnDateDeclarationChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateDeclaration;
        partial void OnDateDeclarationChanging(Nullable<global::System.DateTime> value);
        partial void OnDateDeclarationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> C_IdExercice
        {
            get
            {
                return _C_IdExercice;
            }
            set
            {
                OnC_IdExerciceChanging(value);
                ReportPropertyChanging("C_IdExercice");
                _C_IdExercice = StructuralObject.SetValidValue(value, "C_IdExercice");
                ReportPropertyChanged("C_IdExercice");
                OnC_IdExerciceChanged();
            }
        }
        private Nullable<global::System.Int32> _C_IdExercice;
        partial void OnC_IdExerciceChanging(Nullable<global::System.Int32> value);
        partial void OnC_IdExerciceChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TvaAppBDModel", "FK__deduction___IdPe__46E78A0C", "deduction")]
        public EntityCollection<deduction> deductions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<deduction>("TvaAppBDModel.FK__deduction___IdPe__46E78A0C", "deduction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<deduction>("TvaAppBDModel.FK__deduction___IdPe__46E78A0C", "deduction", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TvaAppBDModel", "FK__periode___IdExer__412EB0B6", "exercice")]
        public exercice exercice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<exercice>("TvaAppBDModel.FK__periode___IdExer__412EB0B6", "exercice").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<exercice>("TvaAppBDModel.FK__periode___IdExer__412EB0B6", "exercice").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<exercice> exerciceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<exercice>("TvaAppBDModel.FK__periode___IdExer__412EB0B6", "exercice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<exercice>("TvaAppBDModel.FK__periode___IdExer__412EB0B6", "exercice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TvaAppBDModel", Name="societe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class societe : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet societe.
        /// </summary>
        /// <param name="idSociete">Valeur initiale de la propriété IdSociete.</param>
        public static societe Createsociete(global::System.Int32 idSociete)
        {
            societe societe = new societe();
            societe.IdSociete = idSociete;
            return societe;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSociete
        {
            get
            {
                return _IdSociete;
            }
            set
            {
                if (_IdSociete != value)
                {
                    OnIdSocieteChanging(value);
                    ReportPropertyChanging("IdSociete");
                    _IdSociete = StructuralObject.SetValidValue(value, "IdSociete");
                    ReportPropertyChanged("IdSociete");
                    OnIdSocieteChanged();
                }
            }
        }
        private global::System.Int32 _IdSociete;
        partial void OnIdSocieteChanging(global::System.Int32 value);
        partial void OnIdSocieteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SiegeSoc
        {
            get
            {
                return _SiegeSoc;
            }
            set
            {
                OnSiegeSocChanging(value);
                ReportPropertyChanging("SiegeSoc");
                _SiegeSoc = StructuralObject.SetValidValue(value, true, "SiegeSoc");
                ReportPropertyChanged("SiegeSoc");
                OnSiegeSocChanged();
            }
        }
        private global::System.String _SiegeSoc;
        partial void OnSiegeSocChanging(global::System.String value);
        partial void OnSiegeSocChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                OnTelChanging(value);
                ReportPropertyChanging("Tel");
                _Tel = StructuralObject.SetValidValue(value, true, "Tel");
                ReportPropertyChanged("Tel");
                OnTelChanged();
            }
        }
        private global::System.String _Tel;
        partial void OnTelChanging(global::System.String value);
        partial void OnTelChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value, true, "Fax");
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private global::System.String _Fax;
        partial void OnFaxChanging(global::System.String value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FormeJuridique
        {
            get
            {
                return _FormeJuridique;
            }
            set
            {
                OnFormeJuridiqueChanging(value);
                ReportPropertyChanging("FormeJuridique");
                _FormeJuridique = StructuralObject.SetValidValue(value, true, "FormeJuridique");
                ReportPropertyChanged("FormeJuridique");
                OnFormeJuridiqueChanged();
            }
        }
        private global::System.String _FormeJuridique;
        partial void OnFormeJuridiqueChanging(global::System.String value);
        partial void OnFormeJuridiqueChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdFiscal
        {
            get
            {
                return _IdFiscal;
            }
            set
            {
                OnIdFiscalChanging(value);
                ReportPropertyChanging("IdFiscal");
                _IdFiscal = StructuralObject.SetValidValue(value, "IdFiscal");
                ReportPropertyChanged("IdFiscal");
                OnIdFiscalChanged();
            }
        }
        private Nullable<global::System.Int32> _IdFiscal;
        partial void OnIdFiscalChanging(Nullable<global::System.Int32> value);
        partial void OnIdFiscalChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumTaxPro
        {
            get
            {
                return _NumTaxPro;
            }
            set
            {
                OnNumTaxProChanging(value);
                ReportPropertyChanging("NumTaxPro");
                _NumTaxPro = StructuralObject.SetValidValue(value, "NumTaxPro");
                ReportPropertyChanged("NumTaxPro");
                OnNumTaxProChanged();
            }
        }
        private Nullable<global::System.Int32> _NumTaxPro;
        partial void OnNumTaxProChanging(Nullable<global::System.Int32> value);
        partial void OnNumTaxProChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Regime
        {
            get
            {
                return _Regime;
            }
            set
            {
                OnRegimeChanging(value);
                ReportPropertyChanging("Regime");
                _Regime = StructuralObject.SetValidValue(value, true, "Regime");
                ReportPropertyChanged("Regime");
                OnRegimeChanged();
            }
        }
        private global::System.String _Regime;
        partial void OnRegimeChanging(global::System.String value);
        partial void OnRegimeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ice
        {
            get
            {
                return _Ice;
            }
            set
            {
                OnIceChanging(value);
                ReportPropertyChanging("Ice");
                _Ice = StructuralObject.SetValidValue(value, "Ice");
                ReportPropertyChanged("Ice");
                OnIceChanged();
            }
        }
        private Nullable<global::System.Int32> _Ice;
        partial void OnIceChanging(Nullable<global::System.Int32> value);
        partial void OnIceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RegistreCommerce
        {
            get
            {
                return _RegistreCommerce;
            }
            set
            {
                OnRegistreCommerceChanging(value);
                ReportPropertyChanging("RegistreCommerce");
                _RegistreCommerce = StructuralObject.SetValidValue(value, "RegistreCommerce");
                ReportPropertyChanged("RegistreCommerce");
                OnRegistreCommerceChanged();
            }
        }
        private Nullable<global::System.Int32> _RegistreCommerce;
        partial void OnRegistreCommerceChanging(Nullable<global::System.Int32> value);
        partial void OnRegistreCommerceChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumCnss
        {
            get
            {
                return _NumCnss;
            }
            set
            {
                OnNumCnssChanging(value);
                ReportPropertyChanging("NumCnss");
                _NumCnss = StructuralObject.SetValidValue(value, "NumCnss");
                ReportPropertyChanged("NumCnss");
                OnNumCnssChanged();
            }
        }
        private Nullable<global::System.Int32> _NumCnss;
        partial void OnNumCnssChanging(Nullable<global::System.Int32> value);
        partial void OnNumCnssChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModComptable
        {
            get
            {
                return _ModComptable;
            }
            set
            {
                OnModComptableChanging(value);
                ReportPropertyChanging("ModComptable");
                _ModComptable = StructuralObject.SetValidValue(value, true, "ModComptable");
                ReportPropertyChanged("ModComptable");
                OnModComptableChanged();
            }
        }
        private global::System.String _ModComptable;
        partial void OnModComptableChanging(global::System.String value);
        partial void OnModComptableChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoginDGI
        {
            get
            {
                return _LoginDGI;
            }
            set
            {
                OnLoginDGIChanging(value);
                ReportPropertyChanging("LoginDGI");
                _LoginDGI = StructuralObject.SetValidValue(value, true, "LoginDGI");
                ReportPropertyChanged("LoginDGI");
                OnLoginDGIChanged();
            }
        }
        private global::System.String _LoginDGI;
        partial void OnLoginDGIChanging(global::System.String value);
        partial void OnLoginDGIChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MdpDgi
        {
            get
            {
                return _MdpDgi;
            }
            set
            {
                OnMdpDgiChanging(value);
                ReportPropertyChanging("MdpDgi");
                _MdpDgi = StructuralObject.SetValidValue(value, true, "MdpDgi");
                ReportPropertyChanged("MdpDgi");
                OnMdpDgiChanged();
            }
        }
        private global::System.String _MdpDgi;
        partial void OnMdpDgiChanging(global::System.String value);
        partial void OnMdpDgiChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Capital
        {
            get
            {
                return _Capital;
            }
            set
            {
                OnCapitalChanging(value);
                ReportPropertyChanging("Capital");
                _Capital = StructuralObject.SetValidValue(value, "Capital");
                ReportPropertyChanged("Capital");
                OnCapitalChanged();
            }
        }
        private Nullable<global::System.Decimal> _Capital;
        partial void OnCapitalChanging(Nullable<global::System.Decimal> value);
        partial void OnCapitalChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Activite
        {
            get
            {
                return _Activite;
            }
            set
            {
                OnActiviteChanging(value);
                ReportPropertyChanging("Activite");
                _Activite = StructuralObject.SetValidValue(value, true, "Activite");
                ReportPropertyChanged("Activite");
                OnActiviteChanged();
            }
        }
        private global::System.String _Activite;
        partial void OnActiviteChanging(global::System.String value);
        partial void OnActiviteChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TypeRegime
        {
            get
            {
                return _TypeRegime;
            }
            set
            {
                OnTypeRegimeChanging(value);
                ReportPropertyChanging("TypeRegime");
                _TypeRegime = StructuralObject.SetValidValue(value, true, "TypeRegime");
                ReportPropertyChanged("TypeRegime");
                OnTypeRegimeChanged();
            }
        }
        private global::System.String _TypeRegime;
        partial void OnTypeRegimeChanging(global::System.String value);
        partial void OnTypeRegimeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String commune
        {
            get
            {
                return _commune;
            }
            set
            {
                OncommuneChanging(value);
                ReportPropertyChanging("commune");
                _commune = StructuralObject.SetValidValue(value, true, "commune");
                ReportPropertyChanged("commune");
                OncommuneChanged();
            }
        }
        private global::System.String _commune;
        partial void OncommuneChanging(global::System.String value);
        partial void OncommuneChanged();

        #endregion

        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TvaAppBDModel", "FK__associe___IdSoci__3B75D760", "associe")]
        public EntityCollection<associe> associes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<associe>("TvaAppBDModel.FK__associe___IdSoci__3B75D760", "associe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<associe>("TvaAppBDModel.FK__associe___IdSoci__3B75D760", "associe", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TvaAppBDModel", "FK__exercice___IdSoc__3E52440B", "exercice")]
        public EntityCollection<exercice> exercices
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<exercice>("TvaAppBDModel.FK__exercice___IdSoc__3E52440B", "exercice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<exercice>("TvaAppBDModel.FK__exercice___IdSoc__3E52440B", "exercice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TvaAppBDModel", Name="utilisateur")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class utilisateur : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet utilisateur.
        /// </summary>
        /// <param name="idUtilisateur">Valeur initiale de la propriété idUtilisateur.</param>
        public static utilisateur Createutilisateur(global::System.Int32 idUtilisateur)
        {
            utilisateur utilisateur = new utilisateur();
            utilisateur.idUtilisateur = idUtilisateur;
            return utilisateur;
        }

        #endregion

        #region Propriétés simples
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idUtilisateur
        {
            get
            {
                return _idUtilisateur;
            }
            set
            {
                if (_idUtilisateur != value)
                {
                    OnidUtilisateurChanging(value);
                    ReportPropertyChanging("idUtilisateur");
                    _idUtilisateur = StructuralObject.SetValidValue(value, "idUtilisateur");
                    ReportPropertyChanged("idUtilisateur");
                    OnidUtilisateurChanged();
                }
            }
        }
        private global::System.Int32 _idUtilisateur;
        partial void OnidUtilisateurChanging(global::System.Int32 value);
        partial void OnidUtilisateurChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, true, "login");
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mot_passe
        {
            get
            {
                return _mot_passe;
            }
            set
            {
                Onmot_passeChanging(value);
                ReportPropertyChanging("mot_passe");
                _mot_passe = StructuralObject.SetValidValue(value, true, "mot_passe");
                ReportPropertyChanged("mot_passe");
                Onmot_passeChanged();
            }
        }
        private global::System.String _mot_passe;
        partial void Onmot_passeChanging(global::System.String value);
        partial void Onmot_passeChanged();

        #endregion

    }

    #endregion

}
